# Generated by Django 6.0.4 on 2026-04-27 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_passwordresettoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresettoken',
            name='token_type',
            field=models.CharField(choices=[('password_reset', 'Password Reset'), ('email_verification', 'Email Verification')], default='password_reset', max_length=20),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['token_type', 'used'], name='core_passwo_token_t_8a6db9_idx'),
        ),
    ]
