# Generated by Django 5.2.3 on 2026-04-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_passwordresettoken_secure_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='otp_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='resend_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
