# Generated by Django 5.2.3 on 2026-04-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_paymentreminder_reminderentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
