# Generated by Django 5.2.3 on 2026-04-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_transaction_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token_type',
            field=models.CharField(choices=[('password_reset', 'Password Reset'), ('email_verification', 'Email Verification'), ('account_deletion', 'Account Deletion')], default='password_reset', max_length=20),
        ),
    ]
